config/routes.rb
Rails.application.routes.draw do
  
  get '/invite' , to: 'groups#invite'
  post '/save_invite' , to: 'groups#save_invite'

  get 'comments/new'

  get 'comments/show'

  get 'comments/index'

  get 'requests/new'

  get 'invitations/new'

  get 'invitations/show'

  post '/search', to: 'invitations#search'

  post '/rsearch' , to: 'requests#search'
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get '/help' , to: 'static_pages#help'

  get '/about' , to: 'static_pages#about'

  get '/contact' , to: 'static_pages#contact'

  get '/signup' , to: 'users#new'

  resources :users

  resources :groups

  resources :invitations

  resources :requests

  resources :posts

  resources :comments
  get '/login' , to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout' , to: 'sessions#destroy'

  post '/respond' , to: 'invitations#respond'

  post '/grant' , to: 'requests#grant'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post 
	belongs_to :user 
end

app/models/group.rb
class Group < ApplicationRecord
	validates :name, presence: true, length: {maximum: 8},
				uniqueness: true

 	has_many :memberships , dependent: :destroy
	has_many :users , :through => :memberships	
	has_many :invitations , dependent: :destroy
	has_many :requests , dependent: :destroy
	has_many :posts , :through => :memberships , dependent: :destroy
	has_many :comments , :through => :posts , dependent: :destroy
end

app/models/invitation.rb
class Invitation < ApplicationRecord
	belongs_to :group
	has_one :sender, :class_name => 'User'
	has_one :receiver, :class_name => 'User'
end

app/models/membership.rb
class Membership < ApplicationRecord
	belongs_to :user
	belongs_to :group
	has_many :posts , dependent: :destroy
	has_many :comments , :through => :posts , dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :membership
	#belongs_to :user  
	#belongs_to :group 
	has_many :comments , dependent: :destroy

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "app/assets/images/missing.png", url: '/public/:filename'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :group
	belongs_to :user , :foreign_key => 'sender_id' 
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:true, length: {maximum:255},format: {with: VALID_EMAIL_REGEX},
									uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }	,allow_nil:true						
	
	has_many :memberships , dependent: :destroy
	has_many :groups , :through => :memberships, dependent: :destroy
	has_many :posts , :through => :memberships , dependent: :destroy
	has_many :comments , dependent: :destroy
	has_many :invites , :class_name => 'Invitation' , :foreign_key => 'sender_id' , dependent: :destroy
	has_many :invitations , :class_name => 'Invitation' , :foreign_key => 'receiver_id' , dependent: :destroy
	has_many :requests , :foreign_key => 'sender_id' , dependent: :destroy
	

	def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def show
  end

  def index
  end

  def create

  	comment = Comment.new(post_id: params[:comment][:p_id].to_i,content: params[:comment][:content],user_id: current_user.id)
  	comment.save
  	post_object = Post.find_by(id: params[:comment][:p_id].to_i)
  	redirect_to post_path(post_object)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	
	def index
		@group_membership_all = Membership.joins(:group).select(:group_id,:name).where(user_id: current_user.id) 
	end

	def show
		@group = Group.find(params[:id])
	end

	def new
		@user = current_user
		@group = Group.new
	end

	def create
		@user = current_user
		@group = Group.new(group_params)
  		if @group.save
      	  flash[:success] = "Created group named #{@group.name}!!"
      	  membership = Membership.new(user_id: @user.id,group_id: @group.id, is_admin: true)
      	  membership.save
      	  session[:group_id] = @group.id
      	  redirect_to new_invitation_path
  		else
  		  render 'new'
  	    end
	end

	def invite
	end









	private 

	def group_params
		params.require(:group).permit(:name)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def show
    
  end

  def index
  end

  def create
    tmp = params[:post][:avatar]
    puts tmp
  	user = current_user.id
  	group = params[:post][:id].to_i
  	membership = Membership.select(:id).where(user_id: user, group_id: group).first
  	post_content = params[:post][:content]
  	new_post = Post.new(content: post_content, membership_id: membership['id'],avatar_file_name:tmp.original_filename)
  	new_post.save
  	group_object = Group.find_by(id: group)
  	redirect_to group_path(group_object)
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def new
  end

  def search
  	name = (params[:request][:name]).downcase
  	result = Group.select(:id).where("lower(name) like ?" , "%#{name}%")
 	flash[:request] = result
  	redirect_to new_request_path
  end

  def create
    request = Request.new(sender_id: current_user.id , group_id: params[:request][:id].to_i)
    request.save
  end

  def index
  end

  def grant
    msg = params[:commit]
    request = Request.find_by(id: params[:request][:id])
    if msg == "Yes"
      request.update_attributes(is_granted: true)
      membership = Membership.new(user_id: params[:request][:sender_id] , group_id: params[:request][:group_id] , is_admin: false)
      membership.save
    else
      request.update_attributes(is_granted: false)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  	  log_in user
  	  redirect_to user
    else
  		flash.now[:danger] = "Invalid email/password combination"
  		render 'new'
  	end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	#@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
      flash[:success] = "Welcome to Discuss!!"
      redirect_to @user
  	else
  		render 'new'
  	end
  end

  def index
  end

  private

  def user_params
  	params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/groups/index.html.erb
<% provide(:title, 'Discuss') %>
<h1>My Groups</h1>

<div class="groups">
    <ul>
    	<% @group_membership_all.each do |group_membership|%>
    	<li>
    		<%# binding.pry %>
    		<% @temp_group = Group.find_by(id:group_membership[:group_id])%>
    		<%= link_to group_membership[:name], group_path(@temp_group) %>
    		<%= group_membership[:group_id] %>
    	</li>
    	<% end %>
    </ul>
</div>

app/views/groups/invite.html.erb
<h1>Invite people</h1>

<div class = "invites">
	<%= form_for(:list,url: add_invite_path) do |f| %>
</div>

app/views/groups/new.html.erb
<% provide(:title, 'Create Group') %>
<h1>Create Group</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@group) do |f| %>
     <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.submit "Create Group", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<% provide(:title , @group) %>
<div class = "row">
	<aside class = "col-md-4">
		<section class = "group_info">
			<h1>
			<%= @group.name %>
			<%= @group.id %>
			</h1>
			 <%= form_for(:post,url: posts_path) do |f| %>
     		 	<%#= render 'shared/error_messages' %>
      			<%= f.hidden_field :id, :value => @group.id%>
      			<%= f.label :name %>
      			<%= f.text_area :content%>
      			<%= f.file_field :avatar %>
      			<%= f.submit "Submit post", class: "btn btn-primary" %>
    		<% end %>
		</section>
	</aside>
</div>

<div class = "posts">
	<% joined_table = Post.joins(:membership).joins("INNER JOIN groups ON Groups.id = Memberships.group_id").order(created_at: :desc)%>
	<% posts = joined_table.select(:id,:group_id,:content,:created_at,:user_id).where("Memberships.group_id = #{@group.id}") %>
	<ul>
		<% posts.each do |post| %>
			<li>
				<% #binding.pry %>
				<%= link_to 'attachement' , Post.last.avatar.url(:original, false) %>
				<%= link_to post['content'] , post_path(post) %> 
				<%= time_ago_in_words(post['created_at']) %>
				<% user = User.select(:id,:name).where(id: post['user_id']).first %>
				posted by <%= link_to user['name'] , user_path(user)%>
			</li>
		<% end %>
	</ul>
</div>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<% @post_object = Post.find(params[:id]) %>
<h1>
	Comments on 
</h1>
<p> <%= @post_object.content %>

<div class = "comments">
	<%= form_for(:comment,url: comments_path) do |f| %>
     	<%#= render 'shared/error_messages' %>
      	<%= f.hidden_field :p_id, :value => @post_object.id%>
      	<%= f.label :comment %>
      	<%= f.text_field :content%>
      	<%= f.submit "Submit comment", class: "btn btn-primary" %>
    <% end %>
</div>

<div class = "comments">
	<% joined_table = Comment.joins(:post).joins("INNER JOIN memberships ON Posts.membership_id = Memberships.id").order(created_at: :desc)%>
	<%  record = Post.joins(:membership).select(:group_id).where(id: params[:id].to_i).first %>
	<%  grp_id = record['group_id'] %>
	<% comments = joined_table.select(:id,:content,:created_at,:user_id).where("Memberships.group_id = #{grp_id} AND Posts.id = #{@post_object.id}") %>
	<ul>
		<% comments.each do |comment| %>
			<li>
				<%= link_to comment['content'] , comment_path(comment) %> 
				<%= time_ago_in_words(comment['created_at']) %>
				<% user = User.select(:id,:name).where(id: comment['user_id']).first %>
				posted by <%= link_to user['name'] , user_path(user)%>
			</li>
		<% end %>
	</ul>
</div>

app/views/requests/index.html.erb
<% provide(:title, 'Discuss') %>
<h1>Requests</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% results = Request.joins("INNER JOIN memberships ON requests.group_id = memberships.group_id").select(:id,:group_id,:sender_id).where("memberships.is_admin=true AND memberships.user_id = #{current_user.id} AND requests.is_granted IS NULL") %>
    <ul>
        <% results.each do |result| %>
        <li>
            <% group_name =  Group.select(:name).where(id: result['group_id'].to_i)%>
            <% user_name =  User.select(:name).where(id: result['user_id'].to_i)%>
            <%= group_name[0]['name']%>
            <%= form_for(:request,url: grant_path) do |f| %>
                <%= f.hidden_field :id, :value => result['id'].to_i%>
                <%= f.hidden_field :group_id, :value => result['group_id'].to_i%>
                <%= f.hidden_field :sender_id, :value => result['sender_id'].to_i%>
                <%= f.submit "Yes", class: "btn btn-primary" %>
                <%= f.submit "No", class: "btn btn-primary" %>
            <% end %>
        </li>
        <% end %>
    </ul>
  </div>
</div>

app/views/requests/new.html.erb
<% provide(:title, 'Discuss') %>
<h1>Search Groups!!!</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:request,url: rsearch_path) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <% if !(flash[:request].nil?) %>
	<ul>
		<% flash[:request].each do |id|%>
			<li>
				<% group = Group.find_by(id: id['id'].to_i) %>
        <%= group.name %>
        <%= form_for(:request,url: requests_path) do |f| %>
          <%= f.hidden_field :id, :value => group.id%>
          <%= f.submit "Request", class: "btn btn-primary" %>
			   <% end %>
      </li>
      <%end%>    
	</ul>
  <%end%>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Discuss') %>
<h1>
	All Users
</h1>

<div class = "users">
	<ul>
		<%  users = User.select(:id,:name) %>
		<% users.each do |user| %>
			<li>
				<%= link_to user['name'] , user_path(user) %>
			</li>
		<% end %>
	</ul>

</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title , @user.name) %>
<div class = "row">
	<aside class = "col-md-4">
		<section class = "user_info">
			<h1>
				<%= gravatar_for @user %>
			<%= @user.name %>		
			</h1>
		</section>
	</aside>
</div>