config/routes.rb
Rails.application.routes.draw do
  
  get '/invite' , to: 'groups#invite'
  post '/save_invite' , to: 'groups#save_invite'

  get 'comments/new'

  get 'comments/show'

  get 'comments/index'

  get 'requests/new'

  get 'invitations/new'

  get 'invitations/show'

  post '/search', to: 'invitations#search'

  post '/rsearch' , to: 'requests#search'
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get '/help' , to: 'static_pages#help'

  get '/about' , to: 'static_pages#about'

  get '/contact' , to: 'static_pages#contact'

  get '/signup' , to: 'users#new'

  resources :users

  resources :groups

  resources :invitations

  resources :requests

  resources :posts

  resources :comments
  get '/login' , to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout' , to: 'sessions#destroy'

  post '/respond' , to: 'invitations#respond'

  post '/grant' , to: 'requests#grant'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post 
	belongs_to :user 
end

app/models/group.rb
class Group < ApplicationRecord
	validates :name, presence: true, length: {maximum: 8},
				uniqueness: true

 	has_many :memberships , dependent: :destroy
	has_many :users , :through => :memberships	
	has_many :invitations , dependent: :destroy
	has_many :requests , dependent: :destroy
	has_many :posts , :through => :memberships , dependent: :destroy
	has_many :comments , :through => :posts , dependent: :destroy
end

app/models/invitation.rb
class Invitation < ApplicationRecord
	belongs_to :group
	has_one :sender, :class_name => 'User'
	has_one :receiver, :class_name => 'User'
end

app/models/membership.rb
class Membership < ApplicationRecord
	belongs_to :user
	belongs_to :group
	has_many :posts , dependent: :destroy
	has_many :comments , :through => :posts , dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :membership
	#belongs_to :user  
	#belongs_to :group 
	has_many :comments , dependent: :destroy

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "app/assets/images/missing.png", url: '/public/:filename'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :group
	belongs_to :user , :foreign_key => 'sender_id' 
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:true, length: {maximum:255},format: {with: VALID_EMAIL_REGEX},
									uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }	,allow_nil:true						
	
	has_many :memberships , dependent: :destroy
	has_many :groups , :through => :memberships, dependent: :destroy
	has_many :posts , :through => :memberships , dependent: :destroy
	has_many :comments , dependent: :destroy
	has_many :invites , :class_name => 'Invitation' , :foreign_key => 'sender_id' , dependent: :destroy
	has_many :invitations , :class_name => 'Invitation' , :foreign_key => 'receiver_id' , dependent: :destroy
	has_many :requests , :foreign_key => 'sender_id' , dependent: :destroy
	

	def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  	end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	
	def index
		@group_membership_all = Membership.joins(:group).select(:group_id,:name).where(user_id: current_user.id) 
	end

	def show
		@group = Group.find(params[:id])
	end

	def new
		@user = current_user
		@group = Group.new
	end

	def create
		@user = current_user
		@group = Group.new(group_params)
  		if @group.save
      	  flash[:success] = "Created group named #{@group.name}!!"
      	  membership = Membership.new(user_id: @user.id,group_id: @group.id, is_admin: true)
      	  membership.save
      	  session[:group_id] = @group.id
      	  redirect_to new_invitation_path
  		else
  		  render 'new'
  	    end
	end

	def invite
	end









	private 

	def group_params
		params.require(:group).permit(:name)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def show
    
  end

  def index
  end

  def create
    tmp = params[:post][:avatar]
    puts tmp
  	user = current_user.id
  	group = params[:post][:id].to_i
  	membership = Membership.select(:id).where(user_id: user, group_id: group).first
  	post_content = params[:post][:content]
  	new_post = Post.new(content: post_content, membership_id: membership['id'],avatar_file_name:tmp.original_filename)
  	new_post.save
  	group_object = Group.find_by(id: group)
  	redirect_to group_path(group_object)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	#@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
      flash[:success] = "Welcome to Discuss!!"
      redirect_to @user
  	else
  		render 'new'
  	end
  end

  def index
  end

  private

  def user_params
  	params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Discuss", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li> 
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class = "dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Dashboard <b class="caret"></b>
          </a>
          <ul class = "dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>

            <li><%= link_to "Settings", '#' %></li>
            <li class="divider"></li>
            <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>

          <li class = "dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Groups <b class="caret"></b>
          </a>
          <ul class = "dropdown-menu">
            <li><%= link_to "Create Group", new_group_path %></li>
            <li><%= link_to "Join Group", new_request_path %></li>
            <li><%= link_to "My Groups", groups_path %></li>
            <li><%= link_to "Invite people", invite_path %></li>
          </ul>
          </li>

          <li class = "dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Notifications <b class="caret"></b>
          </a>
          <ul class = "dropdown-menu">
          <li><%= link_to "Invitations", invitations_path %></li>
          <li><%= link_to "Requests", requests_path %></li>
          </ul>
          </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discuss</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type,message|%>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if (@user.nil?)%>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<% end %>

<% if !(@group.nil?)%>
  <% if @group.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@group.errors.count, "error") %>.
    </div>
    <ul>
    <% @group.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<% end %>